# Config file for default "make" variables

BASE_IMAGE_NAME ?= ubuntu
BASE_IMAGE_TAG ?= latest
BASE_IMAGE ?= ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}

ENV_FILE=".env"

COMPOSE_ARGS ?= ""

COMPOSE_CMD ?= "docker compose ${COMPOSE_ARGS} "

CURR_VER ?= $(shell cat ./VERSION)
DOCKER_DIR ?= .
DOCKER_BUILD_FILE ?= ${DOCKER_DIR}/Dockerfile
DOCKER_COMPOSE_FILE ?= docker-compose.devenv.yml

APT_LIST ?= "bash ssh git rustup python python-pip python3 python3-pip gcc g++ gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gdb gdb-multiarch docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin make cmake"
DOCKER_BUILD_FLAGS ?= ""

DOCKER_LOGIN = ruaine83
DOCKER_PASS = diamond1883

# Build Targets

TARGET ?= amd64
ALL_TARGETS = amd64 aarch64


# Rust Directories
RUST_SRC = "src/"


# C/C++ Directories
C_SRC = ""

# Vanity :)
MAINT_USER ?= $(shell echo $${USER})