# Config file for default "make" variables

BASE_IMAGE_NAME ?= ubuntu
BASE_IMAGE_TAG ?= latest
BASE_IMAGE ?= ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}

CURR_VER ?= $(shell cat ./VERSION)
DOCKER_DIR ?= ./Docker
DOCKER_BUILD_FILE ?= ${DOCKER_DIR}/Dockerfile
DOCKER_COMPOSE_FILE ?= docker-compose.devenv.yml

APT_LIST ?= "rustup python python3-pip gcc g++ gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gdb gdb-multiarch docker.io make cmake"
DOCKER_BUILD_FLAGS ?= ""

DOCKER_LOGIN = ruaine83
DOCKER_PASS = diamond1883

TARGET ?= "aarch64"
ALL_TARGETS = amd64 aarch64


# Rust Directories
RUST_SRC = "src/"


# C/C++ Directories
C_SRC = ""

# Vanity :)
MAINT_USER ?= $(shell echo $${USER})